#!/bin/bash
# prepare the phrase table from alignment and opus

encs=$1
echo $encs
SCRIPT_ROOTDIR=/a/merkur3/thoang/eman/ufal-smt-playground/multi_playground/s.mosesgiza.f282bc2e.20140906-1739/moses/scripts
DIR=$(pwd)

# delete previous tm and temp
rm -rf tm temp

# create a directory
mkdir tm
mkdir tm/csuk

# make symlink from directory to some random folder
mkdir temp
mkdir temp/encs
# there is a difference in the file alignment.gz and the final alignment, there are two extra columns which I have no idea what is the benefit
zcat $DIR/$encs/Opus.encs.ali.gz | cut -f 1 | gzip -c > temp/encs/alignment.custom.gz
ln -sfn $DIR/$encs/Opus.en.tok.gz temp/encs/corpus.src.gz
ln -sfn $DIR/$encs/Opus.cs.tok.gz temp/encs/corpus.tgt.gz

mkdir tm/csuk/model

$SCRIPT_ROOTDIR/training/train-model.perl \
    --force-factored-filenames \
    --first-step 4 --last-step 6 \
    --root-dir tm/csuk \
    --alignment-file=temp/encs/alignment \
    --alignment=custom \
    --corpus=temp/encs/corpus \
    --f src --e tgt --translation-factors 0-0 --decoding-steps t0
